### ISSUE TITLE
crossed cachix

### ISSUE THREAD

**Issue by oneingan** [illegalprime/nixos-on-arm#23]
Hi, I'm using vanilla sd_image vanilla nixos in rpi3+. Use cachix by default. Why cross compiled packages use different cachix than aarch64? Are the outputs different when native vs cross compilations?

Just for curiosity, I'm noob in cross compiling... Thanks for your work.

**Comment by Ericson2314** [comment]
Yes the outputs a different. Nix hashes based on all inputs and doesn't trust anything different (e.g. native cross compilers) to produce the same result.

I may someday propose an *unsafe* workaround for this; i.e. a way to trust without verifying that the native and cross derivations are interchangeable. First, we need the intentional store, which is an open RFC.
