### ISSUE TITLE
Any plans to merge nixpkgs into mainline?

### ISSUE THREAD

**Issue by ziprandom** [illegalprime/nixos-on-arm#25]
I'm fairly new to nix and don't know the mode but do you plan to post a pull request to NixOS? Is there a commitment on the part of NixOS to reach full cross compiling support for these arm architectures and the particular boards?

**Comment by illegalprime** [comment]
Hi @ziprandom! This project isn't active anymore since NixOS's cross compilation support and native ARM support gotten really good since this was started.

I have made pull requests for every feature/fix that has come out of this project, but I don't believe the NixOS project will 'officially' support cross-compiling for specific boards, just cross-comp in general.

That being said if you do have a board that needs cross comp, it's fairly straightforward to build a NixOS image using the examples in this repo.
